version: '3.3'
services:
    gst-by-hi:
        image: bittles999/ubuntu-gstreamer-wyze-script
#        image: bittles999/gst-wyze
        networks:
            - host
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './app/backyard-hi-run.sh:/app/run.sh'
        container_name: 'gst-by-hi'
        restart: unless-stopped
    gst-by-lo:
        image: bittles999/ubuntu-gstreamer-wyze-script
#        image: bittles999/gst-wyze
        networks:
            - host
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './app/backyard-lo-run.sh:/app/run.sh'
        container_name: 'gst-by-lo'
        restart: unless-stopped
    gst-dr-hi:
#        image: bittles999/gst-wyze
        image: bittles999/ubuntu-gstreamer-wyze-script
        networks:
            - host
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './app/driveway-hi-run.sh:/app/run.sh'
        container_name: 'gst-dr-hi'
        restart: unless-stopped
    gst-dr-lo:
        image: bittles999/ubuntu-gstreamer-wyze-script
#        image: bittles999/gst-wyze
        networks:
            - host
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './app/driveway-lo-run.sh:/app/run.sh'
        container_name: 'gst-dr-lo'
        restart: unless-stopped
networks:
    host:
